# Generated by Django 2.0.5 on 2018-08-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joseph_app', '0003_auto_20180807_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
