# Generated by Django 2.0.5 on 2018-08-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joseph_app', '0004_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=16383)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='user',
            name='hobby',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='organizations',
            field=models.TextField(),
        ),
    ]
