# Generated by Django 2.0.5 on 2018-08-08 21:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joseph_app', '0006_auto_20180809_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll_choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 9, 0, 19, 24, 701989)),
        ),
        migrations.AddField(
            model_name='poll_choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joseph_app.Poll'),
        ),
    ]
