# Generated by Django 2.0.5 on 2018-08-08 21:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joseph_app', '0007_auto_20180809_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_poll_choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.IntegerField(default=0)),
                ('choice', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 9, 0, 29, 5, 271139)),
        ),
    ]
