# Generated by Django 2.0.5 on 2018-08-09 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joseph_app', '0009_auto_20180809_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='poll_type',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 9, 14, 48, 44, 959652)),
        ),
    ]
