# Generated by Django 2.1 on 2018-08-09 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joseph_app', '0009_auto_20180809_0109'),
        ('joseph_app', '0011_auto_20180809_2231'),
    ]

    operations = [
    ]
