# Generated by Django 2.0.5 on 2018-08-10 14:30

import datetime
from django.conf import settings
from django.db import migrations, models
import joseph_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('joseph_app', '0014_auto_20180810_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('event_date', models.DateTimeField()),
                ('place', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Event_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_pk', models.IntegerField(default=0)),
                ('has_visited', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=models.SET(joseph_app.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 10, 17, 30, 44, 320352)),
        ),
    ]
