# Generated by Django 2.0.5 on 2018-08-11 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joseph_app', '0017_auto_20180810_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_image',
            name='image',
            field=models.CharField(max_length=511),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.CharField(default=' ', max_length=511),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_image',
            field=models.CharField(default=' ', max_length=511),
        ),
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 11, 13, 29, 45, 775531)),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=511),
        ),
    ]
