# Generated by Django 2.0.5 on 2018-08-22 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joseph_app', '0020_auto_20180818_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('path', models.CharField(default=' ', max_length=500)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2018, 8, 22, 13, 11, 53, 529391))),
                ('size', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 22, 13, 11, 53, 524395)),
        ),
    ]
